version: "3.8"

services:
  database:
    container_name: database-postgre
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # default: /var/lib/postgresql/data better in a subfolder for volume mounts
      # see https://hub.docker.com/_/postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data